### ISSUE TITLE
opencrg dependency 404

### ISSUE THREAD

**Issue by contle** [bartoszek/AUR-chronoengine#1]
The new dependency (opencrg) doesn't work, since dl link is 404:
https://www.asam.net/standard_downloads/standard_download60bf5172732e7_13439.zip

**Comment by bartoszek** [comment]
Looks like the download link gets deprecated, and each user will have to register/download a copy of the source individually 😢 I'll move `opencrg` to optional components and disable it by default.

**Comment by bartoszek** [comment]
Fixed with e9db63e94d270bb977059c0995008af4fb08c0c7
